### ISSUE TITLE
Integrate storytelling with the others modules

### ISSUE THREAD

**Issue by viniciuscostass** [sergioamorim/iface-profile#19]
Profile and friendship modules should report every change. Ex: New friendship, current city change...

**Comment by sergioamorim** [comment]
Friendship methods implemented. Profile methods not yet

**Comment by sergioamorim** [comment]
done

**Comment by sergioamorim** [comment]
error found, fixing

**Comment by sergioamorim** [comment]
errors fixed (or not...)

I was using repositories in a dumb way, but it's over now ;)
