### ISSUE TITLE
Implement Relationship methods.

### ISSUE THREAD

**Issue by lucaspeixotot** [sergioamorim/iface-profile#23]
Build the struct of relationship between two users, with the implementation of proper methods.
OBS: Vinicius Costa as checker.

**Comment by lucaspeixotot** [comment]
Checklist will be created tomorrow.

**Comment by viniciuscostass** [comment]
Kinship logic has been implemented, so profile can filter which value will be suggested to assign someone as a family member

**Comment by lucaspeixotot** [comment]
- [x] Create a new class for reorganize the relationship and relationship type structure.
- [x] Create a GET request for find the friends of a specific user. 
- [x] Create a GET request for given a user have a list of the possible degree of kinship.
- [x] Create a GET requesto for given the sender gender and the receiver degree of kinship, we have a single relationship type object that will be due relationship type of the relationship.
