### ISSUE TITLE
Relationshiptype mapping on logs (for storytelling) and text improvements on other kind of logs

### ISSUE THREAD

**Issue by sergioamorim** [sergioamorim/iface-profile#25]
- [x] modify save method from RelationshipTypeController to create a single log to the sender as she adds someone in the relationships
- [x] modify update method from RelationshipTypeController to create two distinct logs - one for the sender and one for the receiver - as the relationship is approved
- [x] improve text strings in log creation by profile modifications

**Comment by sergioamorim** [comment]
please check if everything is ok and close the issue

**Comment by lucaspeixotot** [comment]
Everything is ok
