### ISSUE TITLE
Prepare needed POST requests

### ISSUE THREAD

**Issue by lucaspeixotot** [sergioamorim/iface-profile#26]
Prepare User Profile, User Academic Profile and User Professional Profile POST requests, so that given a request all of informations are registred in cascate.
**OBS:**Vinicius Costa as checker.

**Comment by lucaspeixotot** [comment]
Checklists will be created tomorrow.

**Comment by lucaspeixotot** [comment]
- [x] Prepare User Profile Post requests
- [x] Prepare User Academic Profile Post requests
- [x] Prepare User Professional Profile Post requests

**Comment by lucaspeixotot** [comment]
@viniciuscosta10100 waiting checking.

**Comment by viniciuscostass** [comment]
Profile services working good. All bonds are being respected.
