### ISSUE TITLE
Develop HTML page for creating a profile

### ISSUE THREAD

**Issue by igortheotonio** [sergioamorim/iface-profile#28]
Build a friendly-user HTML page to create and to edit an user profile

**Comment by igortheotonio** [comment]
- [x] Organize both pages structures on paper
- [x] Develop creation page
- [x] Develop edition page
- [x] Integrate creation with new_user.html
- [x] Integrate edition with user_list.html

**Comment by viniciuscostass** [comment]
Created initial screen, integrated with angularjs, calling a backend service to post the user_profile
