### ISSUE TITLE
Use moment.js to manipulate dates

### ISSUE THREAD

**Issue by viniciuscostass** [sergioamorim/iface-profile#30]
Insert library into the project and configure initial screens to deal with dates appropriately

**Comment by viniciuscosta10100** [comment]
- [ ] Study about moment.js

- [ ] Insert lib into the project

- [ ] Implement some examples to test moment.js

- [ ] Integrate new_profile screen to use it to manipulate dates

**Comment by viniciuscostass** [comment]
Moment.js won't be needed anymore in the project, because it has been discovered that angular can manipulate dates as well. And already has been created directives and filters to threat that.
